using System;
using Manzano;

//ConverterCelsiusparaFahrenheit.Main(args);
//ConverterFahrenheitparaCelsius.Main(args);
//Calcularvolumedalatadeoleo.Main(args);
//Calcularlitrosusadosemviagem.Main(args);
//Calcularprestaçãocomjuros.Main(args);
//TrocarvaloresAeB.Main(args);
//Adiçãoemultiplicaçãocom4numeros.Main(args);
//Calcularvolumedacaixaretangular.Main(args);
//Mostraroantecessordeumnumero.Main(args);
//Converterdolarparareal.Main(args);
//Converterrealparadolar.Main(args);
//Somartresvaloreseapresentarresultadofinal.Main(args);
//QuadradoDaSoma.Main(args);
//OperacoesComQuatroValores.Main(args);
//CalculoNovoSalario.Main(args);
//ApuracaoVotos.Main(args);
//DiferencaMaiorMenor.Main(args);
//VerificarSinal.Main(args);
//MediaComNotaExtra.Main(args);
//MediaComRegras.Main(args);
//EquacaoComValores.Main(args);
//OrdenarValores.Main(args);
//DivisiveisPor2e3.Main(args);
//MaiorMenorDeTres.Main(args);
//ParOuImpar.Main(args);
//VerificaFaixa.Main(args);
//ForaDaFaixa.Main(args);
//SaudacaoGenero.Main(args);
//TabuadaDe1a10.Main(args);
//SomaParesAte500.Main(args);
//SomaImpares0a20.Main(args);
//PotenciasDe3.Main(args);
//PotenciaManual.Main(args);
//SequenciaFibonacci.Main(args);
//CelsiusParaFahrenheit.Main(args);
// MediaDeDezNumeros.Main(args);
// SomaEntre50e70.Main(args);
// AreaResidencia.Main(args);
// CadastroComConfirmacao.Main(args);
// MaiorMenorComInterrupcao.Main(args);
//Quadradosde15a200.Main(args);
//SomatoriodosPares.Main(args);
//DivisiveisPor4.Main(args);
//GraosdeTrigo.Main(args);
//SomatoriodeFatoriais.Main(args);
//SomatorioMediaeTotal.Main(args);
//AreaDaResidencia.Main(args);
//MaioreMenorValor.Main(args);
//DivisaoSemOperador.Main(args);
//Quadrado2de15a200.Main(args);
//Tabuada.Main(args);
//SomaDos100PrimeirosInteiros.Main(args);
//SomatorioDosPares2.Main(args);
//ImparesDe0a20.Main(args);
//Divisiveis2Por4.Main(args);
//PotenciaDe3.Main(args);
//PotenciaGenerica.Main(args);
//SerieDeFibonacci.Main(args);
//CelsiusParaFahrenheit2.Main(args);